# Generated by Django 4.1.7 on 2023-03-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectApp3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30, unique=True)),
                ('color', models.CharField(max_length=20)),
                ('parts_available', models.ManyToManyField(related_name='related_cars_parts', to='projectApp3.carpart')),
            ],
        ),
    ]
