# Generated by Django 4.1.7 on 2023-03-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp3', '0001_initial'),
        ('projectApp2', '0002_alter_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='parts_available',
            field=models.ManyToManyField(related_name='related_cars_parts', to='projectApp3.carpart'),
        ),
    ]
