# Generated by Django 4.1.7 on 2023-03-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp1', '0004_user_password_user_user_name_alter_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
