# Generated by Django 4.1.7 on 2023-03-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(default='https://thumbs.dreamstime.com/z/vector-car-parts-turbocharger-isolated-white-background-vector-car-parts-turbocharger-145918739.jpg', max_length=500)),
                ('car_part_name', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
