# Generated by Django 4.1.7 on 2023-03-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp3', '0002_remove_carpart_car_part_car_model_carpart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpart',
            name='img_url',
            field=models.CharField(default='https://thumbs.dreamstime.com/z/vector-car-parts-turbocharger-isolated-white-background-vector-car-parts-turbocharger-145918739.jpg', max_length=500),
        ),
    ]
