# Generated by Django 4.1.7 on 2023-03-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_part_name', models.CharField(max_length=100, unique=True)),
                ('car_part_car_model', models.CharField(max_length=100)),
            ],
        ),
    ]
